/**
 * _resource_ model generated by Base12
 */

var mongoose = require('mongoose');

var _resource_ = new mongoose.Schema(_props_, {strict: true});   // turn off strict if you would like to store data that isn't in schema


// Export

module.exports = mongoose.model('_resource_', _resource_);